/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.frmCriarProjetoController;

/**
 * Classe que representa a interface gráfica para criar um novo projeto.
 * Utiliza a classe frmCriarProjetoController para controlar as interações e atualizações.
 * 
 * @author Erick Lopes
 */
public class frmCriarProjetoVIEW extends javax.swing.JInternalFrame {

    // Controlador associado a esta interface
    private frmCriarProjetoController controller;

    /**
     * Cria uma nova instância da classe frmCriarProjetoVIEW.
     * Inicializa os componentes da interface e instancia o controlador.
     */
    public frmCriarProjetoVIEW() {
        initComponents();
        controller = new frmCriarProjetoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeProjeto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DataCtrInicio = new com.toedter.calendar.JDateChooser();
        DataCtrPrevisaoTermino = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        LimparCampos = new javax.swing.JButton();
        CadastrarProjeto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoProjeto = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Ações = new javax.swing.JMenu();
        CadastrarProjeto2 = new javax.swing.JMenuItem();
        LimparCampos2 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setTitle("Criar Novo Projeto");

        jLabel1.setText("Nome do Projeto:");

        jLabel2.setText("Data de Inicio:");

        jLabel3.setText("Previsão Término:");

        jLabel4.setText("Descrição do Projeto: ");

        DataCtrInicio.setDateFormatString("dd/MM/yyyy");

        DataCtrPrevisaoTermino.setDateFormatString("dd/MM/yyyy");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Preencha os dados do Projeto");

        LimparCampos.setText("Limpar ");
        LimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCamposActionPerformed(evt);
            }
        });

        CadastrarProjeto.setText("Gravar");
        CadastrarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProjetoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtDescricaoProjeto);

        Ações.setText("Ações");

        CadastrarProjeto2.setText("Gravar");
        CadastrarProjeto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProjeto2ActionPerformed(evt);
            }
        });
        Ações.add(CadastrarProjeto2);

        LimparCampos2.setText("Limpar dados");
        LimparCampos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCampos2ActionPerformed(evt);
            }
        });
        Ações.add(LimparCampos2);

        jMenuBar1.add(Ações);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CadastrarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataCtrPrevisaoTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNomeProjeto)
                            .addComponent(DataCtrInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeProjeto)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DataCtrInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DataCtrPrevisaoTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastrarProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setBounds(450, 100, 405, 430);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpa os campos da interface.
     * Este método é chamado quando o botão "Limpar" é acionado.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void LimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCamposActionPerformed
        controller.limparCampos();
    }//GEN-LAST:event_LimparCamposActionPerformed

    /**
     * Cadastra o projeto com base nos dados preenchidos na interface.
     * Este método é chamado quando o botão "Gravar" é acionado.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void CadastrarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProjetoActionPerformed
        controller.cadastrarProjeto(this);
    }//GEN-LAST:event_CadastrarProjetoActionPerformed

    /**
     * Cadastra o projeto com base nos dados preenchidos na interface.
     * Este método é chamado quando a opção "Gravar" no menu é selecionada.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void CadastrarProjeto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProjeto2ActionPerformed
        controller.cadastrarProjeto(this);
    }//GEN-LAST:event_CadastrarProjeto2ActionPerformed

    /**
     * Limpa os campos da interface.
     * Este método é chamado quando a opção "Limpar dados" no menu é selecionada.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void LimparCampos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCampos2ActionPerformed
        controller.limparCampos();
    }//GEN-LAST:event_LimparCampos2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ações;
    private javax.swing.JButton CadastrarProjeto;
    private javax.swing.JMenuItem CadastrarProjeto2;
    public com.toedter.calendar.JDateChooser DataCtrInicio;
    public com.toedter.calendar.JDateChooser DataCtrPrevisaoTermino;
    private javax.swing.JButton LimparCampos;
    private javax.swing.JMenuItem LimparCampos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JEditorPane txtDescricaoProjeto;
    public javax.swing.JTextField txtNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
