/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import com.mycompany.gqs.a3.GQSA3;
import java.awt.Frame;

/**
 * Classe que representa a interface gráfica de login do sistema.
 * Utiliza a classe GQSA3 como controlador para gerenciar as interações e a lógica.
 * Permite que o usuário entre no sistema ou crie uma nova conta.
 * 
 * @author Erick Lopes
 */
public class frmLoginVIEW extends javax.swing.JFrame {

    // Controlador associado a esta interface
    private GQSA3 controller;

    /**
     * Cria uma nova instância da classe frmLoginVIEW.
     * Inicializa os componentes da interface e instancia o controlador.
     */
    public frmLoginVIEW() {
        initComponents();
        controller = new GQSA3(this); // Inicializa o controlador
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeAcesso = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnEntrarSistema = new javax.swing.JButton();
        BtnCriarUsuario = new javax.swing.JButton();
        txtSenhaUsuario = new javax.swing.JPasswordField();
        MinimizarView = new javax.swing.JButton();
        EncerrarView = new javax.swing.JButton();
        btnMostrarSenha = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txtNomeAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeAcesso);
        txtNomeAcesso.setBounds(80, 110, 220, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 80, 80, 27);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 150, 100, 25);

        BtnEntrarSistema.setBackground(new java.awt.Color(255, 255, 255));
        BtnEntrarSistema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnEntrarSistema.setForeground(new java.awt.Color(0, 0, 0));
        BtnEntrarSistema.setText("Entrar");
        BtnEntrarSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnEntrarSistema.setBorderPainted(false);
        BtnEntrarSistema.setContentAreaFilled(false);
        BtnEntrarSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnEntrarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntrarSistema);
        BtnEntrarSistema.setBounds(80, 230, 60, 30);

        BtnCriarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BtnCriarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BtnCriarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        BtnCriarUsuario.setText("Criar nova conta");
        BtnCriarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCriarUsuario.setBorderPainted(false);
        BtnCriarUsuario.setContentAreaFilled(false);
        BtnCriarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCriarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCriarUsuario);
        BtnCriarUsuario.setBounds(80, 270, 130, 23);
        getContentPane().add(txtSenhaUsuario);
        txtSenhaUsuario.setBounds(80, 180, 220, 22);

        MinimizarView.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MinimizarView.setForeground(new java.awt.Color(0, 0, 0));
        MinimizarView.setText("-");
        MinimizarView.setBorder(null);
        MinimizarView.setBorderPainted(false);
        MinimizarView.setContentAreaFilled(false);
        MinimizarView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MinimizarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarViewActionPerformed(evt);
            }
        });
        getContentPane().add(MinimizarView);
        MinimizarView.setBounds(570, 0, 50, 30);

        EncerrarView.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EncerrarView.setForeground(new java.awt.Color(0, 0, 0));
        EncerrarView.setText("X");
        EncerrarView.setBorder(null);
        EncerrarView.setBorderPainted(false);
        EncerrarView.setContentAreaFilled(false);
        EncerrarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncerrarViewActionPerformed(evt);
            }
        });
        getContentPane().add(EncerrarView);
        EncerrarView.setBounds(620, 0, 50, 30);

        btnMostrarSenha.setText("Visualizar");
        btnMostrarSenha.setBorder(null);
        btnMostrarSenha.setContentAreaFilled(false);
        btnMostrarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarSenha);
        btnMostrarSenha.setBounds(310, 180, 80, 20);
        btnMostrarSenha.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_login.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 670, 380);

        setSize(new java.awt.Dimension(670, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Realiza a ação quando o nome de acesso é inserido.
     * Este método é chamado quando o usuário pressiona Enter após inserir o nome de acesso.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void txtNomeAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAcessoActionPerformed

    /**
     * Realiza a ação quando o botão de entrar no sistema é acionado.
     * Este método chama o método do controlador responsável por fazer login no sistema.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void BtnEntrarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarSistemaActionPerformed
        controller.logar(txtNomeAcesso.getText(), txtSenhaUsuario.getText());
    }//GEN-LAST:event_BtnEntrarSistemaActionPerformed

    /**
     * Realiza a ação quando o botão de criar novo usuário é acionado.
     * Este método chama o método do controlador responsável por abrir a interface de criação de novo usuário.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void BtnCriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCriarUsuarioActionPerformed
        controller.abrirFrmNovoUsuario();
    }//GEN-LAST:event_BtnCriarUsuarioActionPerformed

    /**
     * Realiza a ação quando o botão de encerrar a interface é acionado.
     * Este método encerra a aplicação.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void EncerrarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncerrarViewActionPerformed
        System.exit(0); 

    }//GEN-LAST:event_EncerrarViewActionPerformed

    /**
     * Realiza a ação quando o botão de mostrar/ocultar senha é acionado.
     * Este método chama o método do controlador responsável por mostrar ou ocultar a senha digitada.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void btnMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSenhaActionPerformed
        controller.mostrarSenha();
    }//GEN-LAST:event_btnMostrarSenhaActionPerformed

    /**
     * Realiza a ação quando o botão de minimizar a interface é acionado.
     * Este método minimiza a janela.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void MinimizarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarViewActionPerformed
        this.setState(Frame.ICONIFIED); 
    }//GEN-LAST:event_MinimizarViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCriarUsuario;
    private javax.swing.JButton BtnEntrarSistema;
    private javax.swing.JButton EncerrarView;
    private javax.swing.JButton MinimizarView;
    public javax.swing.JCheckBox btnMostrarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtNomeAcesso;
    public javax.swing.JPasswordField txtSenhaUsuario;
    // End of variables declaration//GEN-END:variables
}
