/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.frmPrincipalController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * A classe `frmPrincipalVIEW` representa a interface gráfica principal do sistema.
 * Permite o gerenciamento de projetos, configurações do usuário e fornece informações adicionais sobre o sistema.
 * Utiliza a classe `frmPrincipalController` como controlador para gerenciar as interações e a lógica.
 * 
 * @author Erick Lopes
 */
public class frmPrincipalVIEW extends javax.swing.JFrame {

    // Controlador associado a esta interface
    private frmPrincipalController controller;

    /**
     * Cria uma nova instância da classe `frmPrincipalVIEW`.
     * Inicializa os componentes da interface e instancia o controlador.
     */
    public frmPrincipalVIEW() {
        initComponents();
        controller = new frmPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1319, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Gerenciamento de Projetos");

        jMenuItem1.setText("Criar Novo Projeto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Consultar Projetos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configurações");

        jMenuItem3.setText("Log out");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobre");

        jMenuItem4.setText("Informações Adicionais");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1335, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Realiza a ação quando o item de menu "Criar Novo Projeto" é selecionado.
     * Este método chama o método do controlador responsável por iniciar o processo de criação de um novo projeto.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        controller.CriarProjeto();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Realiza a ação quando o item de menu "Consultar Projetos" é selecionado.
     * Este método chama o método do controlador responsável por listar os projetos existentes.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        controller.ListarProjeto(); // Passe a instância como argumento
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * Realiza a ação quando o item de menu "Log out" é selecionado.
     * Este método chama o método do controlador responsável por realizar o logout do usuário.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        controller.logout();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * Realiza a ação quando o item de menu "Informações Adicionais" é selecionado.
     * Este método exibe uma mensagem informativa com detalhes sobre a entrega estudantil e um link para informações adicionais.
     * 
     * @param evt O evento de ação que desencadeou este método.
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    String mensagem = """
        Entrega em grupo referente a entrega estudantil, supervisionada pela instrutora Rafaela Moreira.
        """;

    JLabel mensagemLabel = new JLabel(mensagem);
    
    String url = "https://github.com/Projetos-Estudos";
    JLabel urlLabel = new JLabel(url);
    urlLabel.setForeground(Color.BLUE);
    urlLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    
    urlLabel.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() > 0) {
                Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
                if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
                    try {
                        URI uri = new URI(url);
                        desktop.browse(uri);
                    } catch (URISyntaxException | IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        }
    });

    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
    panel.add(mensagemLabel);
    panel.add(urlLabel);
    
    // Exibir uma notificação com as informações
    JOptionPane.showMessageDialog(this, panel, "Notificação Técnica", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}